#!/bin/sh

#  db_copy [-c] source_dir dest_dir
#
#    use to copy wordlist.db and related files
#    from one directory to another

set -e # die on errors

COMPACT=0
while test "$1" ; do
    case "$1" in
	-c) COMPACT=1 ;;
	-*) echo "unknown option $1" >&2 ; exit 1 ;;
	*) break;
    esac
    shift
done

if [ $# -ne 2 ] ; then
    echo usage: db_copy [-c] source_dir dest_dir
    echo "   use -c to copy active logs, not all"
    exit 1
fi

SRC="$1"
DST="$2"

# flush mempools
db_checkpoint -1h "$SRC" || :

mkdir "$DST"

F=bfc.$$.unneeded
rm -f $F
trap "rm -rf $F \"$DST\"" 0
if test $COMPACT -eq 1 ; then
  # don't copy unneeded logs
  db_archive -h "$SRC" >$F
else
  : >$F
fi
LOGS=`ls "$SRC"/log.* | grep -v -F -f $F`
if test "$LOGS" ; then cp -p $LOGS "$DST" ; fi
ENV=`ls "$SRC"/__db.* || :`
if test "$ENV" ; then cp -p $ENV "$DST" ; fi
if test -f "$SRC"/DB_CONFIG ; then cp -p "$SRC"/DB_CONFIG "$DST" ; fi

for FILE in "$SRC"/*.db ; do
    NAME=`basename $FILE`
    SIZE=`db_stat -h "$SRC" -d $NAME | awk '/page size/ {print $1}'`
    dd bs=$SIZE if="$FILE" of="$DST/"`basename "$FILE"`
done

db_recover -h "$DST"
rm -f $F
trap - 0
