#!/bin/sh

#  bf_compact source_dir [wordlist_name]
#
#    use to compact wordlist.db
#    replaces original directory with new one
#    renames original directory with '.old' extension

# $Id$

set -e # die on errors

if [ -z "$1" ] ; then
    echo usage: bf_compact source_dir [wordlist_name]
    exit 1
fi

BOGOHOME="$1"

if [ ! -d $BOGOHOME ] ; then
    echo "$BOGOHOME" must be a directory, not a file
    exit
fi

if [ -z "$2" ] ; then
    FILE="wordlist.db"
else
    FILE="$2"
fi

TEMP="bf_compact.$$"

if [ -d $TEMP ] ; then
    echo Directory $TEMP already exists.
    echo exiting.
    exit 1
else
    mkdir $TEMP
fi

if test -f "$BOGOHOME"/DB_CONFIG ; then cp -p "$BOGOHOME"/DB_CONFIG "$TEMP" ; fi
bogoutil -d "$BOGOHOME"/"$FILE" | bogoutil -l $TEMP/"$FILE"

#checkpoint and remove unneeded log files
bogoutil --db-prune=$TEMP

mv "$BOGOHOME" "$BOGOHOME.old"
mv  $TEMP      "$BOGOHOME"
