#! /bin/sh

# (C) 2004 Matthias Andree, GNU GPL v2
#
# This script, bf_resize, tries to guess useful sizes for the lock
# environment.

# Usage: bf_resize [DIR]
#   DIR defaults to . and is the path of a bogofilter Berkeley database
#   environment.
#
# This script reads all databases in that directory, calculates a lock
# size and writes it to DB_CONFIG, then runs recovery to make the change
# effective.

# environment overrides:
#   DB_ARCHIVE	- path to db_archive to use
#   AWK		- path to awk to use

set -e

DIR=${1:-.}
: ${DB_ARCHIVE:=db_archive}
: ${AWK:=awk}

a=0
dbs=$(db_archive -s -a -h "$DIR")
if [ ! "$dbs" ] ; then
    echo >&2 "No database files in \"$DIR\" found"
    exit 1
fi

for i in $dbs ; do
    pages=$(db_stat -h "$DIR" -d "$i" \
	    | awk '/Number of tree leaf pages/ {print $1;}')
    a=$(( $a + $pages ))
done

# be generous
a=$(( $a * 2 ))

touch "$DIR"/DB_CONFIG
egrep -v '^set_lk_max_(locks|objects)' "$DIR"/DB_CONFIG >"$DIR"/DB_CONFIG.new || true
echo >>"$DIR"/DB_CONFIG.new set_lk_max_locks $a
echo >>"$DIR"/DB_CONFIG.new set_lk_max_objects $a
mv "$DIR"/DB_CONFIG.new "$DIR"/DB_CONFIG
yes
bogoutil --db-recover="$DIR"
