#!/bin/sh

e=".mc"

if [ "$1" = "-h" ] ; then
    printf "       "
    for file in r?.ns; do
	printf "%5s  " `echo $file | sed s@.ns@@`
    done
    printf "\n"
fi

for type in sp ns; do
    printf "%5s  " $type$e
    for file in r?.$type$e; do
	printf "%5d  " `grep -c MSG_COUNT < $file`
    done
    printf "\n"
done
