#!/bin/sh

#  bf_compact source_dir [wordlist_name...]
#
#    use to compact wordlist.db
#    replaces original directory with new one
#    renames original directory with '.old' extension

# $Id$

set -e # die on errors

if [ -z "$1" ] ; then
    echo usage: bf_compact source_dir [wordlist_name...]
    exit 1
fi

BOGOHOME="$1"
shift

if [ ! -d $BOGOHOME ] ; then
    echo "$BOGOHOME must be a directory. Abort."
    exit 1
fi

while true; do
    case $BOGOHOME in
	*/) BOGOHOME=${BOGOHOME%/} ;;
	*)  break ;;
    esac
done

if [ -z "$1" ] ; then
    FILE=$(bogofilter -QQ -d "$BOGOHOME" | grep '^wordlist' | cut -f3 -d,)
else
    FILE="$@"
fi

TEMP="bf_compact.$$"

if ! mkdir "$TEMP" ; then
    echo "Cannot create directory $TEMP. Abort."
    exit 1
fi

if test -f "$BOGOHOME"/DB_CONFIG ; then
    cp -p "$BOGOHOME"/DB_CONFIG "$TEMP"/
fi
for i in $FILE ; do
    bogoutil -d "$BOGOHOME"/"$i" | bogoutil -l $TEMP/"$i"
done

#checkpoint and remove unneeded log files
bogoutil --db-prune=$TEMP

mv "$BOGOHOME" "$BOGOHOME.old"
mv  $TEMP      "$BOGOHOME"
