#! /bin/sh
# (C) 2004 Matthias Andree, GNU GPLv2

# This script updates the bogofilter web directory on sourceforge.

# Theory: check out everything into a staging directory, web,
# then rsync the relevant part into htdocs

set -e
umask 02

cd /home/groups/b/bo/bogofilter/web

CMDPFX="cvs -d :pserver:anonymous@bogofilter.cvs.sourceforge.net:/cvsroot/bogofilter"

# check out
$CMDPFX update -d -P

# start ourselves anew
if [ "x$NORECURSE" = x ] ; then
    env NORECURSE=1 $0
else

  for FILE in bogofilter-faq.html bogofilter-faq-fr.html ; do
    $CMDPFX checkout -p -Dtomorrow bogofilter/doc/$FILE > $FILE
  done
  $CMDPFX checkout -p -Dtomorrow bogofilter/NEWS >NEWS

  # copy without cruft and internal files
  rsync -av --delete ./ ../htdocs/ --delete-excluded \
      --exclude CVS \
      --exclude README_BEFORE_EDITING \
      --exclude .nfs* \
      --exclude updateweb \
      # do not remove this comment - it is for the preceding backslash

fi
