#! /bin/sh
# (C) 2004 Matthias Andree, GNU GPLv2

# This script updates the bogofilter web directory on sourceforge.

# Theory: check out everything into a staging directory, web,
# then rsync the relevant part into htdocs

set -e
umask 02

echo "### CHECKING OUT WEB ###"
cd /home/groups/b/bo/bogofilter/web

CMDPFX="cvs -q -d :pserver:anonymous@bogofilter.cvs.sourceforge.net:/cvsroot/bogofilter"

# check out
$CMDPFX update -d -P

# start ourselves anew
if [ "x$NORECURSE" = x ] ; then
    echo "### RESTARTING $0 ###"
    env NORECURSE=1 $0
else

  echo "### CHECKING OUT FAQ and NEWS ###"
  FILES="bogofilter-faq.html bogofilter-faq-fr.html bogofilter-faq-it.html"
  for FILE in $FILES ; do
    $CMDPFX checkout -p -Dtomorrow bogofilter/doc/$FILE > $FILE
  done
  $CMDPFX checkout -p -Dtomorrow bogofilter/NEWS >NEWS

  echo "### COPYING STAGING AREA TO htdocs/ ###"
  # copy without cruft and internal files
  rsync -aH --delete ./ ../htdocs/ --delete-excluded \
      --exclude CVS --exclude '.#*' \
      --exclude README_BEFORE_EDITING \
      --exclude .nfs* \
      --exclude updateweb \
      --exclude '*~' \
      # do not remove this comment - it is for the preceding backslash

  echo "### DONE ###"
fi
